site_name: Проект Андромеда

theme:
  name: material
  features:
    - toc.integrate # оглавление в левом сайдбаре
    - toc.follow # активный пункт всегда в зоне видимости
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Книга: index.md # один большой файл со всей книгой
